<?php
/*
	This file is the root of the website. Here is the global code generating the
	complete page.
*/

require_once("php/constants.php");
require_once("php/class/htmlbuilder.php");
require_once("php/class/htmlcomponent/menu.php");
require_once("php/util/format.php");


class Example extends DefaultBlockComponent {
	private $innerHtml = '';
	
	public function generateInnerHtml() {
		$content = '';
		$content .= '<h1>'.TITLE.'</h1>';
		$content .= '<div><div><p>Here is    a first	> 	page generated by a PHP class.</p></div></div>';
		$content .= '<img src="" />';
		$this->innerHtml = $content;
	}
	
	public function getInnerHtml() {
		return $this->innerHtml;
	}
}

$menu = new Menu();
$menu->setId('menu');
$menu->addEntry('entry 1', 'link 1');
$menu->addEntry('entry 2', 'link 2');
$menu->addEntry('entry 3', 'link 3');

$builder = new HtmlBuilder();
$builder->setTitle(TITLE);
$builder->addComponent(new Example());
$builder->addComponent($menu);
$builder->generateHtml();
$html = $builder->getHtml();

// TODO debugging
$html = formatHtml($html);
// TODO /debugging
echo $html;
?>
